<?php

/**
 * @file
 * Contains qubit.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function qubit_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the qubit module.
    case 'help.page.qubit':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Qubit tracking integration') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments().
 */
function qubit_page_attachments(array &$attachments) {
  // Add to every page.
  $attachments['#attached']['library'][] = 'qubit/qubit';
}
