<?php

/**
 * @file
 * Contains qubit_lite.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function qubit_lite_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the qubit_lite module.
    case 'help.page.qubit_lite':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A small iframe version of the Qubit tracking integration') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments().
 */
function qubit_lite_page_attachments(array &$attachments) {
  // Not as a library as we need to have a different library for each domain.
  // see https://www.drupal.org/docs/8/creating-custom-modules/adding-stylesheets-css-and-javascript-js-to-a-drupal-8-module#entire-page.

  /** @var Drupal\qubit_lite\Controller\QubitTrackingController $qubit */
  $qubit = \Drupal::service('qubit_lite.tracker');
  if ($qubit->onCurrentPage() && $qubit->getScriptUrl()) {
    $attachments['#attached']['html_head'][] = [
      // The data.
      [
        '#type' => 'html_tag',
        // The HTML tag to add, in this case a  tag.
        '#tag' => 'script',
        // Set attributes like src to load a file.
        '#attributes' => [
          'src' => $qubit->getScriptUrl(),
          'defer' => TRUE,
          'async' => TRUE,
        ],
      ],
      // A key, to make it possible to recognize this HTML element when altering.
      'qubit_lite_opentag',
    ];
  }

}

/**
 * Implements hook_page_bottom().
 */
function qubit_lite_page_bottom(array &$page_bottom) {

  // We need to add the tracking iframe to all pages.
  $qubit = \Drupal::service('qubit_lite.tracker');

  if ($qubit->onCurrentPage()) {
    $page_bottom['qubit_lite'] = [
      '#type' => 'html_tag',
      // The HTML tag to add, in this case a  tag.
      '#tag' => 'iframe',
      // Set attributes like src to load a file.
      '#attributes' => [
        'src' => '/' . $qubit->getIframeUrl(),
        'weight' => '1',
        'height' => '1',
        'style' => 'position:absolute; bottom:0px; left:0px; visibility:hidden',
      ],
    ];
    if ($qubit->loadBiscotti()) {
      $page_bottom['qubit_lite_biscotti'] = [
        '#type' => 'html_tag',
        // The HTML tag to add, in this case a  tag.
        '#tag' => 'iframe',
        // Set attributes like src to load a file.
        '#attributes' => [
          'src' => '/' . $qubit->getBiscottiIframeUrl(),
          'weight' => '1',
          'height' => '1',
          'style' => 'position:absolute; bottom:0px; left:0px; visibility:hidden',
        ],
      ];
    }
  }
}