qubit_lite.settings:
  type: config_object
  mapping:
    customer_id:
      type: string
    site_id:
      type: string
    biscotti_url:
      type: string
    biscotti_safe_domains:
      type: text
